#include <linux/ioctl.h>

#define MAX_IF_NAME 32

#define PKTGENE_TEST_MAGIC_CHAR 'T'
#define PKTGENE_TEST _IO(PKTGENE_TEST_MAGIC_CHAR,1)
#define DATA_ACTION_RANDOM 0x1
#define DATA_ACTION_INCREMENT 0x2
#define DATA_ACTION_DECREMENT 0x3

#define PKTGENE_NETIF_MAGIC_CHAR 'N'
#define PKTGENE_CMD_NETIF_GET_NETDEVICE _IO(PKTGENE_NETIF_MAGIC_CHAR,1)
#define PKTGENE_CMD_NETIF_ATTACH_NETDEVICE _IOW(PKTGENE_NETIF_MAGIC_CHAR,2,int)


#define PKTGENE_TASKBASE_MAGIC_CHAR 'B'
#define PKTGENE_CMD_BASE_TASKBASE_NO _IOW(PKTGENE_TASKBASE_MAGIC_CHAR,1,int)
#define PKTGENE_CMD_BASE_FRAMESIZE _IOW(PKTGENE_TASKBASE_MAGIC_CHAR,2,int)
#define PKTGENE_CMD_BASE_FRAME_BUFF _IO(PKTGENE_TASKBASE_MAGIC_CHAR,3)
#define PKTGENE_CMD_BASE_CSUM		_IOW(PKTGENE_TASKBASE_MAGIC_CHAR,4,int)
#define PKTGENE_CMD_BASE_UPDTAE    _IO(PKTGENE_TASKBASE_MAGIC_CHAR,5)
#define PKTGENE_CMD_BASE_ASSIGN   _IOW(PKTGENE_TASKBASE_MAGIC_CHAR,6,int)
#define PKTGENE_CMD_BASE_MAX_FRAME_NO _IOW(PKTGENE_TASKBASE_MAGIC_CHAR,7,int)

#define PKTGENE_TASKLINE_MAGIC_CHAR 'L'
#define PKTGENE_CMD_LINE_START_NO _IOW(PKTGENE_TASKLINE_MAGIC_CHAR,1,int)
#define PKTGENE_CMD_LINE_END_NO _IOW(PKTGENE_TASKLINE_MAGIC_CHAR,2,int)
#define PKTGENE_CMD_LINE_DATA_TYPE _IOW(PKTGENE_TASKLINE_MAGIC_CHAR,3,int)
#define PKTGENE_CMD_LINE_FRAME_OFFSET _IOW(PKTGENE_TASKLINE_MAGIC_CHAR,4,int)
//#define PKTGENE_CMD_LINE_DATA_LENGTH _IOW(PKTGENE_TASKLINE_MAGIC_CHAR,5,int)
#define PKTGENE_CMD_LINE_CURRENT_VAL _IOW(PKTGENE_TASKLINE_MAGIC_CHAR,6,int)
#define PKTGENE_CMD_LINE_UPDATE _IOW(PKTGENE_TASKLINE_MAGIC_CHAR,7,int)
#define PKTGENE_CMD_LINE_DATA_ACTION_AND_SEEK _IOW(PKTGENE_TASKLINE_MAGIC_CHAR,8,int)


#define PKTGENE_GLOBAL_MAGIC_CHAR 'G'
#define PKTGENE_CMD_GLOBAL_SETRUNINGMASK _IOW(PKTGENE_GLOBAL_MAGIC_CHAR,1,int)
#define PKTGENE_CMD_GLOBAL_RESET _IO(PKTGENE_GLOBAL_MAGIC_CHAR,2)




